apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "three-tier.fullname" . }}-backend
  namespace: {{ .Values.global.environment }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: backend
      env: {{ .Values.global.environment }}
  template:
    metadata:
      labels:
        app: backend
        env: {{ .Values.global.environment }}
    spec:
      containers:
        - name: backend
          image: ghcr.io/{{ .Values.image.repositoryOwner }}/backend:{{ .Values.image.tag }}
          imagePullPolicy: Always
          env:
            - name: APP_ENV
              value: {{ .Values.global.environment | quote }}
            - name: DB_HOST
              value: "{{ include "three-tier.fullname" . }}-db-svc"
            - name: REDIS_HOST
              value: "{{ include "three-tier.fullname" . }}-redis-svc"
            - name: DB_USER
              value: {{ .Values.db.user | quote }}
            - name: DB_PASSWORD
              value: {{ .Values.db.password | quote }}
            - name: DB_NAME
              value: {{ .Values.db.dbName | quote }}
          ports:
            - containerPort: 5000
