apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "three-tier.fullname" . }}-pv
spec:
  capacity:
    storage: {{ .Values.storage.capacity }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.storage.storageClassName }}
  hostPath:
    path: {{ .Values.storage.hostPath }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "three-tier.fullname" . }}-pvc
  namespace: {{ .Values.global.environment }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.storage.capacity }}
